<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace GRPC\Docker;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>docker.dto.AddRequest</code>
 */
class AddRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string repo = 1;</code>
     */
    protected $repo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $repo
     * }
     */
    public function __construct($data = NULL) {
        \GRPC\Docker\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string repo = 1;</code>
     * @return string
     */
    public function getRepo()
    {
        return $this->repo;
    }

    /**
     * Generated from protobuf field <code>string repo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRepo($var)
    {
        GPBUtil::checkString($var, True);
        $this->repo = $var;

        return $this;
    }

}

