<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: service.proto

namespace GRPC\Docker;

use Spiral\RoadRunner\GRPC;

interface DockerServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "docker.DockerService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \GRPC\Docker\AddRequest $in
    * @return \GRPC\Docker\AddResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Add(GRPC\ContextInterface $ctx, \GRPC\Docker\AddRequest $in): \GRPC\Docker\AddResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \GRPC\Docker\RemoveRequest $in
    * @return \GRPC\Docker\RemoveResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Remove(GRPC\ContextInterface $ctx, \GRPC\Docker\RemoveRequest $in): \GRPC\Docker\RemoveResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \GRPC\Docker\AllRequest $in
    * @return \GRPC\Docker\AllResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function All(GRPC\ContextInterface $ctx, \GRPC\Docker\AllRequest $in): \GRPC\Docker\AllResponse;
}
