{
 "title": "Docker",
 "templating": {
  "list": [
   { "name": "repository", "query": { "query": "docker_downloads" } }
  ]
 },
 "panels": [
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_downloads", "legendFormat": "{{repo}}" }
   ]
  },
  {
   "title": "Last 24 hours downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(docker_downloads{repo=\"$repository\"}[24h])",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_downloads{repo=\"$repository\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_stars{repo=\"$repository\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "delta(docker_downloads{repo=\"$repository\"}[24h])",
     "legendFormat": "{{repo}}"
    }
   ]
  }
 ]
}