<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace GRPC\Docker\GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af5010a0d6d6573736167652e70726f746f120a646f636b65722e64746f221a0a0a41646452657175657374120c0a047265706f180120012809221d0a0b416464526573706f6e7365120e0a06737461747573180120012808221d0a0d52656d6f766552657175657374120c0a047265706f18012001280922200a0e52656d6f7665526573706f6e7365120e0a06737461747573180120012808220c0a0a416c6c52657175657374221c0a0b416c6c526573706f6e7365120d0a057265706f731801200328094228ca020b475250435c446f636b6572e20217475250435c446f636b65725c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

