<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace GRPC\Docker\GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GRPC\Docker\GPBMetadata\Message::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92020a0d736572766963652e70726f746f1206646f636b657232c6010a0d446f636b65725365727669636512380a0341646412162e646f636b65722e64746f2e416464526571756573741a172e646f636b65722e64746f2e416464526573706f6e7365220012410a0652656d6f766512192e646f636b65722e64746f2e52656d6f7665526571756573741a1a2e646f636b65722e64746f2e52656d6f7665526573706f6e7365220012380a03416c6c12162e646f636b65722e64746f2e416c6c526571756573741a172e646f636b65722e64746f2e416c6c526573706f6e736522004228ca020b475250435c446f636b6572e20217475250435c446f636b65725c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

